/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Points : The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Points {
    /// The number of Amazon Points.
    #[serde(rename = "pointsNumber", skip_serializing_if = "Option::is_none")]
    pub points_number: Option<i32>,
    #[serde(rename = "pointsMonetaryValue", skip_serializing_if = "Option::is_none")]
    pub points_monetary_value: Option<Box<models::product_pricing_2022_05_01::MoneyType>>,
}

impl Points {
    /// The number of Amazon Points that are offered with the purchase of an item and the monetary value of these points.
    pub fn new() -> Points {
        Points {
            points_number: None,
            points_monetary_value: None,
        }
    }
}

