/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrimeDetails : Amazon Prime details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrimeDetails {
    /// Indicates whether the offer is an Amazon Prime offer.
    #[serde(rename = "eligibility")]
    pub eligibility: Eligibility,
}

impl PrimeDetails {
    /// Amazon Prime details.
    pub fn new(eligibility: Eligibility) -> PrimeDetails {
        PrimeDetails {
            eligibility,
        }
    }
}
/// Indicates whether the offer is an Amazon Prime offer.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Eligibility {
    #[serde(rename = "NATIONAL")]
    National,
    #[serde(rename = "REGIONAL")]
    Regional,
    #[serde(rename = "NONE")]
    None,
}

impl Default for Eligibility {
    fn default() -> Eligibility {
        Self::National
    }
}

