/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferencePrice : The reference price for the specified ASIN `marketplaceId` combination.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferencePrice {
    /// Reference price type (e.g., `CompetitivePriceThreshold`, `WasPrice`, `CompetitivePrice`). For definitions, see the [Product Pricing API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "price")]
    pub price: Box<models::product_pricing_2022_05_01::MoneyType>,
}

impl ReferencePrice {
    /// The reference price for the specified ASIN `marketplaceId` combination.
    pub fn new(name: String, price: models::product_pricing_2022_05_01::MoneyType) -> ReferencePrice {
        ReferencePrice {
            name,
            price: Box::new(price),
        }
    }
}

