/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SampleLocation : Information about a location. It uses a postal code to identify the location.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SampleLocation {
    #[serde(rename = "postalCode", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Box<models::product_pricing_2022_05_01::PostalCode>>,
}

impl SampleLocation {
    /// Information about a location. It uses a postal code to identify the location.
    pub fn new() -> SampleLocation {
        SampleLocation {
            postal_code: None,
        }
    }
}

