/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-05-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShippingOption : The shipping option available for the offer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShippingOption {
    /// The type of shipping option.
    #[serde(rename = "shippingOptionType")]
    pub shipping_option_type: ShippingOptionType,
    #[serde(rename = "price")]
    pub price: Box<models::product_pricing_2022_05_01::MoneyType>,
}

impl ShippingOption {
    /// The shipping option available for the offer.
    pub fn new(shipping_option_type: ShippingOptionType, price: models::product_pricing_2022_05_01::MoneyType) -> ShippingOption {
        ShippingOption {
            shipping_option_type,
            price: Box::new(price),
        }
    }
}
/// The type of shipping option.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShippingOptionType {
    #[serde(rename = "DEFAULT")]
    Default,
}

impl Default for ShippingOptionType {
    fn default() -> ShippingOptionType {
        Self::Default
    }
}

