/*
 * Selling Partner API for Data Kiosk
 *
 * The Selling Partner API for Data Kiosk lets you submit GraphQL queries from a variety of schemas to help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2023-11-15
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetQueriesResponse : The response for the `getQueries` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetQueriesResponse {
    /// A list of queries.
    #[serde(rename = "queries")]
    pub queries: Vec<models::data_kiosk_2023_11_15::Query>,
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::data_kiosk_2023_11_15::GetQueriesResponsePagination>>,
}

impl GetQueriesResponse {
    /// The response for the `getQueries` operation.
    pub fn new(queries: Vec<models::data_kiosk_2023_11_15::Query>) -> GetQueriesResponse {
        GetQueriesResponse {
            queries,
            pagination: None,
        }
    }
}

