/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AsinBadge : A flag that provides additional information about an ASIN. This is contextual and can change depending on the request that generated it.
/// A flag that provides additional information about an ASIN. This is contextual and can change depending on the request that generated it.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AsinBadge {
    #[serde(rename = "BRAND_NOT_ELIGIBLE")]
    BrandNotEligible,
    #[serde(rename = "CATALOG_NOT_FOUND")]
    CatalogNotFound,
    #[serde(rename = "CONTENT_NOT_PUBLISHED")]
    ContentNotPublished,
    #[serde(rename = "CONTENT_PUBLISHED")]
    ContentPublished,

}

impl std::fmt::Display for AsinBadge {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BrandNotEligible => write!(f, "BRAND_NOT_ELIGIBLE"),
            Self::CatalogNotFound => write!(f, "CATALOG_NOT_FOUND"),
            Self::ContentNotPublished => write!(f, "CONTENT_NOT_PUBLISHED"),
            Self::ContentPublished => write!(f, "CONTENT_PUBLISHED"),
        }
    }
}

impl Default for AsinBadge {
    fn default() -> AsinBadge {
        Self::BrandNotEligible
    }
}

