/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentBadge : A flag that provides additional information about an A+ Content document.
/// A flag that provides additional information about an A+ Content document.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentBadge {
    #[serde(rename = "BULK")]
    Bulk,
    #[serde(rename = "GENERATED")]
    Generated,
    #[serde(rename = "LAUNCHPAD")]
    Launchpad,
    #[serde(rename = "PREMIUM")]
    Premium,
    #[serde(rename = "STANDARD")]
    Standard,

}

impl std::fmt::Display for ContentBadge {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bulk => write!(f, "BULK"),
            Self::Generated => write!(f, "GENERATED"),
            Self::Launchpad => write!(f, "LAUNCHPAD"),
            Self::Premium => write!(f, "PREMIUM"),
            Self::Standard => write!(f, "STANDARD"),
        }
    }
}

impl Default for ContentBadge {
    fn default() -> ContentBadge {
        Self::Bulk
    }
}

