/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentModule : An A+ Content module. An A+ Content document is composed of content modules. The `contentModuleType` property selects which content module types to use.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentModule {
    #[serde(rename = "contentModuleType")]
    pub content_module_type: models::aplus_content_2020_11_01::ContentModuleType,
    #[serde(rename = "standardCompanyLogo", skip_serializing_if = "Option::is_none")]
    pub standard_company_logo: Option<Box<models::aplus_content_2020_11_01::StandardCompanyLogoModule>>,
    #[serde(rename = "standardComparisonTable", skip_serializing_if = "Option::is_none")]
    pub standard_comparison_table: Option<Box<models::aplus_content_2020_11_01::StandardComparisonTableModule>>,
    #[serde(rename = "standardFourImageText", skip_serializing_if = "Option::is_none")]
    pub standard_four_image_text: Option<Box<models::aplus_content_2020_11_01::StandardFourImageTextModule>>,
    #[serde(rename = "standardFourImageTextQuadrant", skip_serializing_if = "Option::is_none")]
    pub standard_four_image_text_quadrant: Option<Box<models::aplus_content_2020_11_01::StandardFourImageTextQuadrantModule>>,
    #[serde(rename = "standardHeaderImageText", skip_serializing_if = "Option::is_none")]
    pub standard_header_image_text: Option<Box<models::aplus_content_2020_11_01::StandardHeaderImageTextModule>>,
    #[serde(rename = "standardImageSidebar", skip_serializing_if = "Option::is_none")]
    pub standard_image_sidebar: Option<Box<models::aplus_content_2020_11_01::StandardImageSidebarModule>>,
    #[serde(rename = "standardImageTextOverlay", skip_serializing_if = "Option::is_none")]
    pub standard_image_text_overlay: Option<Box<models::aplus_content_2020_11_01::StandardImageTextOverlayModule>>,
    #[serde(rename = "standardMultipleImageText", skip_serializing_if = "Option::is_none")]
    pub standard_multiple_image_text: Option<Box<models::aplus_content_2020_11_01::StandardMultipleImageTextModule>>,
    #[serde(rename = "standardProductDescription", skip_serializing_if = "Option::is_none")]
    pub standard_product_description: Option<Box<models::aplus_content_2020_11_01::StandardProductDescriptionModule>>,
    #[serde(rename = "standardSingleImageHighlights", skip_serializing_if = "Option::is_none")]
    pub standard_single_image_highlights: Option<Box<models::aplus_content_2020_11_01::StandardSingleImageHighlightsModule>>,
    #[serde(rename = "standardSingleImageSpecsDetail", skip_serializing_if = "Option::is_none")]
    pub standard_single_image_specs_detail: Option<Box<models::aplus_content_2020_11_01::StandardSingleImageSpecsDetailModule>>,
    #[serde(rename = "standardSingleSideImage", skip_serializing_if = "Option::is_none")]
    pub standard_single_side_image: Option<Box<models::aplus_content_2020_11_01::StandardSingleSideImageModule>>,
    #[serde(rename = "standardTechSpecs", skip_serializing_if = "Option::is_none")]
    pub standard_tech_specs: Option<Box<models::aplus_content_2020_11_01::StandardTechSpecsModule>>,
    #[serde(rename = "standardText", skip_serializing_if = "Option::is_none")]
    pub standard_text: Option<Box<models::aplus_content_2020_11_01::StandardTextModule>>,
    #[serde(rename = "standardThreeImageText", skip_serializing_if = "Option::is_none")]
    pub standard_three_image_text: Option<Box<models::aplus_content_2020_11_01::StandardThreeImageTextModule>>,
}

impl ContentModule {
    /// An A+ Content module. An A+ Content document is composed of content modules. The `contentModuleType` property selects which content module types to use.
    pub fn new(content_module_type: models::aplus_content_2020_11_01::ContentModuleType) -> ContentModule {
        ContentModule {
            content_module_type,
            standard_company_logo: None,
            standard_comparison_table: None,
            standard_four_image_text: None,
            standard_four_image_text_quadrant: None,
            standard_header_image_text: None,
            standard_image_sidebar: None,
            standard_image_text_overlay: None,
            standard_multiple_image_text: None,
            standard_product_description: None,
            standard_single_image_highlights: None,
            standard_single_image_specs_detail: None,
            standard_single_side_image: None,
            standard_tech_specs: None,
            standard_text: None,
            standard_three_image_text: None,
        }
    }
}

