/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StandardComparisonProductBlock : The A+ Content standard comparison product block.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardComparisonProductBlock {
    /// The rank or index of this comparison product block within the module. Different blocks cannot occupy the same position within a single module.
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<Box<models::aplus_content_2020_11_01::ImageComponent>>,
    /// The comparison product title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The Amazon Standard Identification Number (ASIN).
    #[serde(rename = "asin", skip_serializing_if = "Option::is_none")]
    pub asin: Option<String>,
    /// When true, indicates that this content block is visually highlighted.
    #[serde(rename = "highlight", skip_serializing_if = "Option::is_none")]
    pub highlight: Option<bool>,
    /// Comparison metrics for the product.
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<models::aplus_content_2020_11_01::PlainTextItem>>,
}

impl StandardComparisonProductBlock {
    /// The A+ Content standard comparison product block.
    pub fn new(position: i32) -> StandardComparisonProductBlock {
        StandardComparisonProductBlock {
            position,
            image: None,
            title: None,
            asin: None,
            highlight: None,
            metrics: None,
        }
    }
}

