/*
 * Selling Partner API for A+ Content Management
 *
 * Use the A+ Content API to build applications that help selling partners add rich marketing content to their Amazon product detail pages. Selling partners can use A+ content to share their brand and product story, which helps buyers make informed purchasing decisions. Selling partners use content modules to add images and text.
 *
 * The version of the OpenAPI document: 2020-11-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StandardTextModule : A standard headline and body text.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardTextModule {
    #[serde(rename = "headline", skip_serializing_if = "Option::is_none")]
    pub headline: Option<Box<models::aplus_content_2020_11_01::TextComponent>>,
    #[serde(rename = "body")]
    pub body: Box<models::aplus_content_2020_11_01::ParagraphComponent>,
}

impl StandardTextModule {
    /// A standard headline and body text.
    pub fn new(body: models::aplus_content_2020_11_01::ParagraphComponent) -> StandardTextModule {
        StandardTextModule {
            headline: None,
            body: Box::new(body),
        }
    }
}

