/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CarrierId : The unique carrier code for the carrier for whom container labels are requested.
/// The unique carrier code for the carrier for whom container labels are requested.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CarrierId {
    #[serde(rename = "SWA")]
    Swa,

}

impl std::fmt::Display for CarrierId {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Swa => write!(f, "SWA"),
        }
    }
}

impl Default for CarrierId {
    fn default() -> CarrierId {
        Self::Swa
    }
}

