/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Package : The package that is associated with the container.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Package {
    /// The tracking number on the label of shipment package, that you can fetch from the `shippingLabels` response. You can also scan the bar code on the shipping label to get the tracking number.
    #[serde(rename = "packageTrackingNumber")]
    pub package_tracking_number: String,
}

impl Package {
    /// The package that is associated with the container.
    pub fn new(package_tracking_number: String) -> Package {
        Package {
            package_tracking_number,
        }
    }
}

