/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Use the Selling Partner API for Direct Fulfillment Shipping to access a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: 2021-12-28
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartyIdentification : The name, address, and tax details of a party.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyIdentification {
    /// The identifier of the party.
    #[serde(rename = "partyId")]
    pub party_id: String,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::vendor_direct_fulfillment_shipping_2021_12_28::Address>>,
    /// The tax registration details of the party.
    #[serde(rename = "taxRegistrationDetails", skip_serializing_if = "Option::is_none")]
    pub tax_registration_details: Option<Vec<models::vendor_direct_fulfillment_shipping_2021_12_28::TaxRegistrationDetails>>,
}

impl PartyIdentification {
    /// The name, address, and tax details of a party.
    pub fn new(party_id: String) -> PartyIdentification {
        PartyIdentification {
            party_id,
            address: None,
            tax_registration_details: None,
        }
    }
}

