/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetPurchaseOrdersResponse : The response schema for the getPurchaseOrders operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPurchaseOrdersResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::vendor_orders::OrderList>>,
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::vendor_orders::Error>>,
}

impl GetPurchaseOrdersResponse {
    /// The response schema for the getPurchaseOrders operation.
    pub fn new() -> GetPurchaseOrdersResponse {
        GetPurchaseOrdersResponse {
            payload: None,
            errors: None,
        }
    }
}

