/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AsinIdentifier : Schema to identify an item by MarketPlaceId and ASIN.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AsinIdentifier {
    /// A marketplace identifier.
    #[serde(rename = "MarketplaceId")]
    pub marketplace_id: String,
    /// The Amazon Standard Identification Number (ASIN) of the item.
    #[serde(rename = "ASIN")]
    pub asin: String,
}

impl AsinIdentifier {
    /// Schema to identify an item by MarketPlaceId and ASIN.
    pub fn new(marketplace_id: String, asin: String) -> AsinIdentifier {
        AsinIdentifier {
            marketplace_id,
            asin,
        }
    }
}

