/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetItemOffersBatchResponse : The response associated with the `getItemOffersBatch` API call.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetItemOffersBatchResponse {
    /// A list of `getItemOffers` batched responses.
    #[serde(rename = "responses", skip_serializing_if = "Option::is_none")]
    pub responses: Option<Vec<models::product_pricing_v0::ItemOffersResponse>>,
}

impl GetItemOffersBatchResponse {
    /// The response associated with the `getItemOffersBatch` API call.
    pub fn new() -> GetItemOffersBatchResponse {
        GetItemOffersBatchResponse {
            responses: None,
        }
    }
}

