/*
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferCustomerType : Indicates whether the offer is a B2B or B2C offer
/// Indicates whether the offer is a B2B or B2C offer
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OfferCustomerType {
    #[serde(rename = "B2C")]
    B2C,
    #[serde(rename = "B2B")]
    B2B,

}

impl std::fmt::Display for OfferCustomerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::B2C => write!(f, "B2C"),
            Self::B2B => write!(f, "B2B"),
        }
    }
}

impl Default for OfferCustomerType {
    fn default() -> OfferCustomerType {
        Self::B2C
    }
}

