/*
 * Selling Partner API for Retail Procurement Transaction Status
 *
 * The Selling Partner API for Retail Procurement Transaction Status provides programmatic access to status information on specific asynchronous POST transactions for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionStatus : Represents the status of a transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionStatus {
    #[serde(rename = "transactionStatus", skip_serializing_if = "Option::is_none")]
    pub transaction_status: Option<Box<models::vendor_transaction_status::Transaction>>,
}

impl TransactionStatus {
    /// Represents the status of a transaction.
    pub fn new() -> TransactionStatus {
        TransactionStatus {
            transaction_status: None,
        }
    }
}

