/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListTransactionsResponse : The response schema for the `listTransactions` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListTransactionsResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::finances_2024_06_19::TransactionsPayload>>,
}

impl ListTransactionsResponse {
    /// The response schema for the `listTransactions` operation.
    pub fn new() -> ListTransactionsResponse {
        ListTransactionsResponse {
            payload: None,
        }
    }
}

