/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarketplaceDetails : Information about the marketplace where the transaction occurred.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketplaceDetails {
    /// The identifier of the marketplace where the transaction occurred. The marketplace ID is the globally unique identifier of a marketplace. To find the ID for your marketplace, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
    #[serde(rename = "marketplaceId", skip_serializing_if = "Option::is_none")]
    pub marketplace_id: Option<String>,
    /// The name of the marketplace where the transaction occurred.   Example: 'Amazon.com','Amazon.in'
    #[serde(rename = "marketplaceName", skip_serializing_if = "Option::is_none")]
    pub marketplace_name: Option<String>,
}

impl MarketplaceDetails {
    /// Information about the marketplace where the transaction occurred.
    pub fn new() -> MarketplaceDetails {
        MarketplaceDetails {
            marketplace_id: None,
            marketplace_name: None,
        }
    }
}

