/*
 * The Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order or date range without having to wait until a statement period closes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProductContext : Additional information related to the product.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductContext {
    /// Amazon Standard Identification Number (ASIN) of the item.
    #[serde(rename = "asin", skip_serializing_if = "Option::is_none")]
    pub asin: Option<String>,
    /// Stock keeping unit (SKU) of the item.
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<String>,
    /// Quantity of the item shipped.
    #[serde(rename = "quantityShipped", skip_serializing_if = "Option::is_none")]
    pub quantity_shipped: Option<i32>,
    /// Fulfillment network of the item.
    #[serde(rename = "fulfillmentNetwork", skip_serializing_if = "Option::is_none")]
    pub fulfillment_network: Option<String>,
}

impl ProductContext {
    /// Additional information related to the product.
    pub fn new() -> ProductContext {
        ProductContext {
            asin: None,
            sku: None,
            quantity_shipped: None,
            fulfillment_network: None,
        }
    }
}

