/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateInventoryItemRequest : An item to be created in the inventory.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInventoryItemRequest {
    /// The seller SKU of the item.
    #[serde(rename = "sellerSku")]
    pub seller_sku: String,
    /// The marketplaceId.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// The name of the item.
    #[serde(rename = "productName")]
    pub product_name: String,
}

impl CreateInventoryItemRequest {
    /// An item to be created in the inventory.
    pub fn new(seller_sku: String, marketplace_id: String, product_name: String) -> CreateInventoryItemRequest {
        CreateInventoryItemRequest {
            seller_sku,
            marketplace_id,
            product_name,
        }
    }
}

