/*
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InventoryItem : An item in the list of inventory to be added.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InventoryItem {
    /// The seller SKU of the item.
    #[serde(rename = "sellerSku")]
    pub seller_sku: String,
    /// The marketplaceId.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// The quantity of item to add.
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl InventoryItem {
    /// An item in the list of inventory to be added.
    pub fn new(seller_sku: String, marketplace_id: String, quantity: i32) -> InventoryItem {
        InventoryItem {
            seller_sku,
            marketplace_id,
            quantity,
        }
    }
}

