/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeliveryPreferences : The delivery preferences applied to the destination address. These preferences are applied when possible and are best effort. This feature is currently supported only in the JP marketplace and not applicable for other marketplaces. For eligible orders, the default delivery preference will be to deliver the package unattended at the front door, unless you specify otherwise.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryPreferences {
    /// Additional delivery instructions. For example, this could be instructions on how to enter a building, nearby landmark or navigation instructions, 'Beware of dogs', etc.
    #[serde(rename = "deliveryInstructions", skip_serializing_if = "Option::is_none")]
    pub delivery_instructions: Option<String>,
    #[serde(rename = "dropOffLocation", skip_serializing_if = "Option::is_none")]
    pub drop_off_location: Option<Box<models::fulfillment_outbound_2020_07_01::DropOffLocation>>,
}

impl DeliveryPreferences {
    /// The delivery preferences applied to the destination address. These preferences are applied when possible and are best effort. This feature is currently supported only in the JP marketplace and not applicable for other marketplaces. For eligible orders, the default delivery preference will be to deliver the package unattended at the front door, unless you specify otherwise.
    pub fn new() -> DeliveryPreferences {
        DeliveryPreferences {
            delivery_instructions: None,
            drop_off_location: None,
        }
    }
}

