/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Destination : The destination for the delivery offer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Destination {
    #[serde(rename = "deliveryAddress", skip_serializing_if = "Option::is_none")]
    pub delivery_address: Option<Box<models::fulfillment_outbound_2020_07_01::VariablePrecisionAddress>>,
    /// An IP Address.
    #[serde(rename = "ipAddress", skip_serializing_if = "Option::is_none")]
    pub ip_address: Option<String>,
}

impl Destination {
    /// The destination for the delivery offer.
    pub fn new() -> Destination {
        Destination {
            delivery_address: None,
            ip_address: None,
        }
    }
}

