/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidItemReasonCode : A code for why the item is invalid for return.
/// A code for why the item is invalid for return.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvalidItemReasonCode {
    #[serde(rename = "InvalidValues")]
    InvalidValues,
    #[serde(rename = "DuplicateRequest")]
    DuplicateRequest,
    #[serde(rename = "NoCompletedShipItems")]
    NoCompletedShipItems,
    #[serde(rename = "NoReturnableQuantity")]
    NoReturnableQuantity,

}

impl std::fmt::Display for InvalidItemReasonCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::InvalidValues => write!(f, "InvalidValues"),
            Self::DuplicateRequest => write!(f, "DuplicateRequest"),
            Self::NoCompletedShipItems => write!(f, "NoCompletedShipItems"),
            Self::NoReturnableQuantity => write!(f, "NoReturnableQuantity"),
        }
    }
}

impl Default for InvalidItemReasonCode {
    fn default() -> InvalidItemReasonCode {
        Self::InvalidValues
    }
}

