/*
 * Selling Partner APIs for Fulfillment Outbound
 *
 * The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitFulfillmentOrderStatusUpdateRequest : The request body schema for the `submitFulfillmentOrderStatusUpdate` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitFulfillmentOrderStatusUpdateRequest {
    #[serde(rename = "fulfillmentOrderStatus", skip_serializing_if = "Option::is_none")]
    pub fulfillment_order_status: Option<models::fulfillment_outbound_2020_07_01::FulfillmentOrderStatus>,
}

impl SubmitFulfillmentOrderStatusUpdateRequest {
    /// The request body schema for the `submitFulfillmentOrderStatusUpdate` operation.
    pub fn new() -> SubmitFulfillmentOrderStatusUpdateRequest {
        SubmitFulfillmentOrderStatusUpdateRequest {
            fulfillment_order_status: None,
        }
    }
}

