/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BrowseNodeReviewSubtopicMetrics : The browse node review subtopic metrics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrowseNodeReviewSubtopicMetrics {
    /// The percentage of reviews that mention the subtopic.
    #[serde(rename = "occurrencePercentage")]
    pub occurrence_percentage: f32,
}

impl BrowseNodeReviewSubtopicMetrics {
    /// The browse node review subtopic metrics.
    pub fn new(occurrence_percentage: f32) -> BrowseNodeReviewSubtopicMetrics {
        BrowseNodeReviewSubtopicMetrics {
            occurrence_percentage,
        }
    }
}

