/*
 * The Selling Partner API for CustomerFeedback
 *
 * The Selling Partner API for Customer Feedback (Customer Feedback API) provides information about customer reviews and returns at both the item and browse node level.
 *
 * The version of the OpenAPI document: 2024-06-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemReviewTopicMetrics : The item review topic metrics.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemReviewTopicMetrics {
    /// The number of times that reviews mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
    #[serde(rename = "numberOfMentions", skip_serializing_if = "Option::is_none")]
    pub number_of_mentions: Option<i32>,
    /// The percentage of customer reviews that mention the topic. This value is `null` if reviews do not mention the topic frequently enough.
    #[serde(rename = "occurrencePercentage", skip_serializing_if = "Option::is_none")]
    pub occurrence_percentage: Option<f32>,
    /// The effect of the topic on the star rating of the ASIN. This value can be positive or negative. This value is `null` if the topic does't affect the star rating of the ASIN.
    #[serde(rename = "starRatingImpact", skip_serializing_if = "Option::is_none")]
    pub star_rating_impact: Option<f32>,
}

impl ItemReviewTopicMetrics {
    /// The item review topic metrics.
    pub fn new() -> ItemReviewTopicMetrics {
        ItemReviewTopicMetrics {
            number_of_mentions: None,
            occurrence_percentage: None,
            star_rating_impact: None,
        }
    }
}

