/*
 * Selling Partner API for Messaging
 *
 * With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetSchemaResponseLinks : The links response that is associated with the object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSchemaResponseLinks {
    #[serde(rename = "self")]
    pub param_self: Box<models::messaging::LinkObject>,
}

impl GetSchemaResponseLinks {
    /// The links response that is associated with the object.
    pub fn new(param_self: models::messaging::LinkObject) -> GetSchemaResponseLinks {
        GetSchemaResponseLinks {
            param_self: Box::new(param_self),
        }
    }
}

