/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateReportScheduleResponse : Response schema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateReportScheduleResponse {
    /// The identifier for the report schedule. This identifier is unique only in combination with a seller ID.
    #[serde(rename = "reportScheduleId")]
    pub report_schedule_id: String,
}

impl CreateReportScheduleResponse {
    /// Response schema.
    pub fn new(report_schedule_id: String) -> CreateReportScheduleResponse {
        CreateReportScheduleResponse {
            report_schedule_id,
        }
    }
}

