/*
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * The version of the OpenAPI document: 2021-06-30
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportScheduleList : A list of report schedules.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportScheduleList {
    /// Detailed information about a report schedule.
    #[serde(rename = "reportSchedules")]
    pub report_schedules: Vec<models::reports_2021_06_30::ReportSchedule>,
}

impl ReportScheduleList {
    /// A list of report schedules.
    pub fn new(report_schedules: Vec<models::reports_2021_06_30::ReportSchedule>) -> ReportScheduleList {
        ReportScheduleList {
            report_schedules,
        }
    }
}

