/*
 * Selling Partner API for Direct Fulfillment Payments
 *
 * The Selling Partner API for Direct Fulfillment Payments provides programmatic access to a direct fulfillment vendor's invoice data.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvoiceItem : Provides the details of the items in this invoice.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceItem {
    /// Numbering of the item on the purchase order. The first item will be 1, the second 2, and so on.
    #[serde(rename = "itemSequenceNumber")]
    pub item_sequence_number: String,
    /// Buyer's standard identification number (ASIN) of an item.
    #[serde(rename = "buyerProductIdentifier", skip_serializing_if = "Option::is_none")]
    pub buyer_product_identifier: Option<String>,
    /// The vendor selected product identification of the item.
    #[serde(rename = "vendorProductIdentifier", skip_serializing_if = "Option::is_none")]
    pub vendor_product_identifier: Option<String>,
    #[serde(rename = "invoicedQuantity")]
    pub invoiced_quantity: Box<models::vendor_direct_fulfillment_payments_v1::ItemQuantity>,
    #[serde(rename = "netCost")]
    pub net_cost: Box<models::vendor_direct_fulfillment_payments_v1::Money>,
    /// The purchase order number for this order. Formatting Notes: 8-character alpha-numeric code.
    #[serde(rename = "purchaseOrderNumber")]
    pub purchase_order_number: String,
    /// The vendor's order number for this order.
    #[serde(rename = "vendorOrderNumber", skip_serializing_if = "Option::is_none")]
    pub vendor_order_number: Option<String>,
    /// Harmonized System of Nomenclature (HSN) tax code. The HSN number cannot contain alphabets.
    #[serde(rename = "hsnCode", skip_serializing_if = "Option::is_none")]
    pub hsn_code: Option<String>,
    /// Individual tax details per line item.
    #[serde(rename = "taxDetails", skip_serializing_if = "Option::is_none")]
    pub tax_details: Option<Vec<models::vendor_direct_fulfillment_payments_v1::TaxDetail>>,
    /// Individual charge details per line item.
    #[serde(rename = "chargeDetails", skip_serializing_if = "Option::is_none")]
    pub charge_details: Option<Vec<models::vendor_direct_fulfillment_payments_v1::ChargeDetails>>,
}

impl InvoiceItem {
    /// Provides the details of the items in this invoice.
    pub fn new(item_sequence_number: String, invoiced_quantity: models::vendor_direct_fulfillment_payments_v1::ItemQuantity, net_cost: models::vendor_direct_fulfillment_payments_v1::Money, purchase_order_number: String) -> InvoiceItem {
        InvoiceItem {
            item_sequence_number,
            buyer_product_identifier: None,
            vendor_product_identifier: None,
            invoiced_quantity: Box::new(invoiced_quantity),
            net_cost: Box::new(net_cost),
            purchase_order_number,
            vendor_order_number: None,
            hsn_code: None,
            tax_details: None,
            charge_details: None,
        }
    }
}

