/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Benefits : Benefits that are included and excluded for each shipping offer. Benefits represents services provided by Amazon (eg. CLAIMS_PROTECTED, etc.) when sellers purchase shipping through Amazon. Benefit details will be made available for any shipment placed on or after January 1st 2024 00:00 UTC.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Benefits {
    /// A list of included benefits.
    #[serde(rename = "includedBenefits")]
    pub included_benefits: Vec<String>,
    /// A list of excluded benefit. Refer to the ExcludeBenefit object for further documentation
    #[serde(rename = "excludedBenefits")]
    pub excluded_benefits: Vec<models::shipping_v2::ExcludedBenefit>,
}

impl Benefits {
    /// Benefits that are included and excluded for each shipping offer. Benefits represents services provided by Amazon (eg. CLAIMS_PROTECTED, etc.) when sellers purchase shipping through Amazon. Benefit details will be made available for any shipment placed on or after January 1st 2024 00:00 UTC.
    pub fn new(included_benefits: Vec<String>, excluded_benefits: Vec<models::shipping_v2::ExcludedBenefit>) -> Benefits {
        Benefits {
            included_benefits,
            excluded_benefits,
        }
    }
}

