/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CarrierAccountInput : Info About CarrierAccountInput
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CarrierAccountInput {
    /// descriptionLocalizationKey value .
    #[serde(rename = "descriptionLocalizationKey", skip_serializing_if = "Option::is_none")]
    pub description_localization_key: Option<String>,
    /// name value .
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// groupName value .
    #[serde(rename = "groupName", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    #[serde(rename = "inputType", skip_serializing_if = "Option::is_none")]
    pub input_type: Option<models::shipping_v2::InputType>,
    /// mandatory or not  value .
    #[serde(rename = "isMandatory", skip_serializing_if = "Option::is_none")]
    pub is_mandatory: Option<bool>,
    /// is value is Confidential .
    #[serde(rename = "isConfidential", skip_serializing_if = "Option::is_none")]
    pub is_confidential: Option<bool>,
    /// is value is hidden .
    #[serde(rename = "isHidden", skip_serializing_if = "Option::is_none")]
    pub is_hidden: Option<bool>,
    /// A list of ValidationMetadata
    #[serde(rename = "validationMetadata", skip_serializing_if = "Option::is_none")]
    pub validation_metadata: Option<Vec<models::shipping_v2::ValidationMetadata>>,
}

impl CarrierAccountInput {
    /// Info About CarrierAccountInput
    pub fn new() -> CarrierAccountInput {
        CarrierAccountInput {
            description_localization_key: None,
            name: None,
            group_name: None,
            input_type: None,
            is_mandatory: None,
            is_confidential: None,
            is_hidden: None,
            validation_metadata: None,
        }
    }
}

