/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCollectionFormHistoryResponse : The Response  for the GetCollectionFormHistoryResponse operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCollectionFormHistoryResponse {
    /// A list of CollectionFormsHistoryRecord
    #[serde(rename = "collectionFormsHistoryRecordList", skip_serializing_if = "Option::is_none")]
    pub collection_forms_history_record_list: Option<Vec<models::shipping_v2::CollectionFormsHistoryRecord>>,
    /// Last Refereshed Date of collection
    #[serde(rename = "lastRefreshedDate", skip_serializing_if = "Option::is_none")]
    pub last_refreshed_date: Option<String>,
}

impl GetCollectionFormHistoryResponse {
    /// The Response  for the GetCollectionFormHistoryResponse operation.
    pub fn new() -> GetCollectionFormHistoryResponse {
        GetCollectionFormHistoryResponse {
            collection_forms_history_record_list: None,
            last_refreshed_date: None,
        }
    }
}

