/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAccessPointsResponse : The response schema for the GetAccessPoints operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccessPointsResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::shipping_v2::GetAccessPointsResult>>,
}

impl GetAccessPointsResponse {
    /// The response schema for the GetAccessPoints operation.
    pub fn new() -> GetAccessPointsResponse {
        GetAccessPointsResponse {
            payload: None,
        }
    }
}

