/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PackageDocument : A document related to a package.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageDocument {
    #[serde(rename = "type")]
    pub r#type: models::shipping_v2::DocumentType,
    #[serde(rename = "format")]
    pub format: models::shipping_v2::DocumentFormat,
    /// A Base64 encoded string of the file contents.
    #[serde(rename = "contents")]
    pub contents: String,
}

impl PackageDocument {
    /// A document related to a package.
    pub fn new(r#type: models::shipping_v2::DocumentType, format: models::shipping_v2::DocumentFormat, contents: String) -> PackageDocument {
        PackageDocument {
            r#type,
            format,
            contents,
        }
    }
}

