/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RateItemType : Type of the rateItem.
/// Type of the rateItem.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RateItemType {
    #[serde(rename = "MANDATORY")]
    Mandatory,
    #[serde(rename = "OPTIONAL")]
    Optional,
    #[serde(rename = "INCLUDED")]
    Included,

}

impl std::fmt::Display for RateItemType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Mandatory => write!(f, "MANDATORY"),
            Self::Optional => write!(f, "OPTIONAL"),
            Self::Included => write!(f, "INCLUDED"),
        }
    }
}

impl Default for RateItemType {
    fn default() -> RateItemType {
        Self::Mandatory
    }
}

