/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestedValueAddedService : A value-added service to be applied to a shipping service purchase.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestedValueAddedService {
    /// The identifier of the selected value-added service. Must be among those returned in the response to the getRates operation.
    #[serde(rename = "id")]
    pub id: String,
}

impl RequestedValueAddedService {
    /// A value-added service to be applied to a shipping service purchase.
    pub fn new(id: String) -> RequestedValueAddedService {
        RequestedValueAddedService {
            id,
        }
    }
}

