/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettlementType : Type of settlement the shipper wants to receive for a particular shipment.
/// Type of settlement the shipper wants to receive for a particular shipment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SettlementType {
    #[serde(rename = "REFUND")]
    Refund,
    #[serde(rename = "CERTIFICATE_OF_FACT")]
    CertificateOfFact,

}

impl std::fmt::Display for SettlementType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Refund => write!(f, "REFUND"),
            Self::CertificateOfFact => write!(f, "CERTIFICATE_OF_FACT"),
        }
    }
}

impl Default for SettlementType {
    fn default() -> SettlementType {
        Self::Refund
    }
}

