/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeWindow : The start and end time that specifies the time interval of an event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeWindow {
    /// The start time of the time window.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    /// The end time of the time window.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
}

impl TimeWindow {
    /// The start and end time that specifies the time interval of an event.
    pub fn new() -> TimeWindow {
        TimeWindow {
            start: None,
            end: None,
        }
    }
}

