/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrackingDetailCodes : Contains detail codes that provide additional details related to the forward and return leg of the shipment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrackingDetailCodes {
    /// Contains detail codes that provide additional details related to the forward leg of the shipment.
    #[serde(rename = "forward")]
    pub forward: Vec<models::shipping_v2::DetailCodes>,
    /// Contains detail codes that provide additional details related to the return leg of the shipment.
    #[serde(rename = "returns")]
    pub returns: Vec<models::shipping_v2::DetailCodes>,
}

impl TrackingDetailCodes {
    /// Contains detail codes that provide additional details related to the forward and return leg of the shipment.
    pub fn new(forward: Vec<models::shipping_v2::DetailCodes>, returns: Vec<models::shipping_v2::DetailCodes>) -> TrackingDetailCodes {
        TrackingDetailCodes {
            forward,
            returns,
        }
    }
}

