/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnmanifestedShipmentLocation : UnmanifestedShipmentLocation info 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnmanifestedShipmentLocation {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::shipping_v2::Address>>,
    /// Its Last Manifest Date.
    #[serde(rename = "lastManifestDate", skip_serializing_if = "Option::is_none")]
    pub last_manifest_date: Option<String>,
}

impl UnmanifestedShipmentLocation {
    /// UnmanifestedShipmentLocation info 
    pub fn new() -> UnmanifestedShipmentLocation {
        UnmanifestedShipmentLocation {
            address: None,
            last_manifest_date: None,
        }
    }
}

