/*
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * The version of the OpenAPI document: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationMetadata : ValidationMetadata Details
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationMetadata {
    /// errorMessage for the error.
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    /// validationStrategy for the error.
    #[serde(rename = "validationStrategy", skip_serializing_if = "Option::is_none")]
    pub validation_strategy: Option<String>,
    /// Value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl ValidationMetadata {
    /// ValidationMetadata Details
    pub fn new() -> ValidationMetadata {
        ValidationMetadata {
            error_message: None,
            validation_strategy: None,
            value: None,
        }
    }
}

