/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Dimension : The value of an individual dimension for an Amazon catalog item or item package.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Dimension {
    /// Unit of measurement for the dimension value.
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// Numeric value of the dimension.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
}

impl Dimension {
    /// The value of an individual dimension for an Amazon catalog item or item package.
    pub fn new() -> Dimension {
        Dimension {
            unit: None,
            value: None,
        }
    }
}

