/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemContributor : Individual contributor to the creation of an item, such as an author or actor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemContributor {
    #[serde(rename = "role")]
    pub role: Box<models::catalog_items_2022_04_01::ItemContributorRole>,
    /// Name of the contributor, such as `Jane Austen`.
    #[serde(rename = "value")]
    pub value: String,
}

impl ItemContributor {
    /// Individual contributor to the creation of an item, such as an author or actor.
    pub fn new(role: models::catalog_items_2022_04_01::ItemContributorRole, value: String) -> ItemContributor {
        ItemContributor {
            role: Box::new(role),
            value,
        }
    }
}

