/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssociationType : The type of association an item has with an order item.
/// The type of association an item has with an order item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AssociationType {
    #[serde(rename = "VALUE_ADD_SERVICE")]
    ValueAddService,

}

impl std::fmt::Display for AssociationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ValueAddService => write!(f, "VALUE_ADD_SERVICE"),
        }
    }
}

impl Default for AssociationType {
    fn default() -> AssociationType {
        Self::ValueAddService
    }
}

