/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OpenTimeInterval : The time when the business opens or closes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OpenTimeInterval {
    /// The hour when the business opens or closes.
    #[serde(rename = "Hour", skip_serializing_if = "Option::is_none")]
    pub hour: Option<i32>,
    /// The minute when the business opens or closes.
    #[serde(rename = "Minute", skip_serializing_if = "Option::is_none")]
    pub minute: Option<i32>,
}

impl OpenTimeInterval {
    /// The time when the business opens or closes.
    pub fn new() -> OpenTimeInterval {
        OpenTimeInterval {
            hour: None,
            minute: None,
        }
    }
}

