/*
 * Selling Partner API for Orders
 *
 * Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreferredDeliveryTime : The time window when the delivery is preferred.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreferredDeliveryTime {
    /// Business hours when the business is open for deliveries.
    #[serde(rename = "BusinessHours", skip_serializing_if = "Option::is_none")]
    pub business_hours: Option<Vec<models::orders_v0::BusinessHours>>,
    /// Dates when the business is closed during the next 30 days.
    #[serde(rename = "ExceptionDates", skip_serializing_if = "Option::is_none")]
    pub exception_dates: Option<Vec<models::orders_v0::ExceptionDates>>,
}

impl PreferredDeliveryTime {
    /// The time window when the delivery is preferred.
    pub fn new() -> PreferredDeliveryTime {
        PreferredDeliveryTime {
            business_hours: None,
            exception_dates: None,
        }
    }
}

