/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BoxContentsSource : Where the seller provided box contents information for a shipment.
/// Where the seller provided box contents information for a shipment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BoxContentsSource {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "FEED")]
    Feed,
    #[serde(rename = "2D_BARCODE")]
    Variant2DBarcode,
    #[serde(rename = "INTERACTIVE")]
    Interactive,

}

impl std::fmt::Display for BoxContentsSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "NONE"),
            Self::Feed => write!(f, "FEED"),
            Self::Variant2DBarcode => write!(f, "2D_BARCODE"),
            Self::Interactive => write!(f, "INTERACTIVE"),
        }
    }
}

impl Default for BoxContentsSource {
    fn default() -> BoxContentsSource {
        Self::None
    }
}

