/*
 * Selling Partner API for Fulfillment Inbound
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelDownloadUrl : Download URL for a label
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelDownloadUrl {
    /// URL to download the label for the package. Note: The URL will only be valid for 15 seconds
    #[serde(rename = "DownloadURL", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
}

impl LabelDownloadUrl {
    /// Download URL for a label
    pub fn new() -> LabelDownloadUrl {
        LabelDownloadUrl {
            download_url: None,
        }
    }
}

