/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemProcurement : The vendor procurement information for the listings item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemProcurement {
    #[serde(rename = "costPrice")]
    pub cost_price: Box<models::listings_items_2021_08_01::Money>,
}

impl ItemProcurement {
    /// The vendor procurement information for the listings item.
    pub fn new(cost_price: models::listings_items_2021_08_01::Money) -> ItemProcurement {
        ItemProcurement {
            cost_price: Box::new(cost_price),
        }
    }
}

