/*
 * Selling Partner API for Listings Items
 *
 * The Selling Partner API for Listings Items (Listings Items API) provides programmatic access to selling partner listings on Amazon. Use this API in collaboration with the Selling Partner API for Product Type Definitions, which you use to retrieve the information about Amazon product types needed to use the Listings Items API.  For more information, see the [Listings Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2021-08-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListingsItemSubmissionResponse : Response containing the results of a submission to the Selling Partner API for Listings Items.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListingsItemSubmissionResponse {
    /// A selling partner provided identifier for an Amazon listing.
    #[serde(rename = "sku")]
    pub sku: String,
    /// The status of the listings item submission.
    #[serde(rename = "status")]
    pub status: Status,
    /// The unique identifier of the listings item submission.
    #[serde(rename = "submissionId")]
    pub submission_id: String,
    /// Listings item issues related to the listings item submission.
    #[serde(rename = "issues", skip_serializing_if = "Option::is_none")]
    pub issues: Option<Vec<models::listings_items_2021_08_01::Issue>>,
    /// Identity attributes associated with the item in the Amazon catalog, such as the ASIN.
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Vec<models::listings_items_2021_08_01::ItemIdentifiersByMarketplace>>,
}

impl ListingsItemSubmissionResponse {
    /// Response containing the results of a submission to the Selling Partner API for Listings Items.
    pub fn new(sku: String, status: Status, submission_id: String) -> ListingsItemSubmissionResponse {
        ListingsItemSubmissionResponse {
            sku,
            status,
            submission_id,
            issues: None,
            identifiers: None,
        }
    }
}
/// The status of the listings item submission.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ACCEPTED")]
    Accepted,
    #[serde(rename = "INVALID")]
    Invalid,
    #[serde(rename = "VALID")]
    Valid,
}

impl Default for Status {
    fn default() -> Status {
        Self::Accepted
    }
}

