/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OperationalConfiguration : The operational configuration of `supplySources`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationalConfiguration {
    #[serde(rename = "contactDetails", skip_serializing_if = "Option::is_none")]
    pub contact_details: Option<Box<models::supply_sources_2020_07_01::ContactDetails>>,
    #[serde(rename = "throughputConfig", skip_serializing_if = "Option::is_none")]
    pub throughput_config: Option<Box<models::supply_sources_2020_07_01::ThroughputConfig>>,
    #[serde(rename = "operatingHoursByDay", skip_serializing_if = "Option::is_none")]
    pub operating_hours_by_day: Option<Box<models::supply_sources_2020_07_01::OperatingHoursByDay>>,
    #[serde(rename = "handlingTime", skip_serializing_if = "Option::is_none")]
    pub handling_time: Option<Box<models::supply_sources_2020_07_01::Duration>>,
}

impl OperationalConfiguration {
    /// The operational configuration of `supplySources`.
    pub fn new() -> OperationalConfiguration {
        OperationalConfiguration {
            contact_details: None,
            throughput_config: None,
            operating_hours_by_day: None,
            handling_time: None,
        }
    }
}

