/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParkingSpotIdentificationType : The type of parking spot identification.
/// The type of parking spot identification.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParkingSpotIdentificationType {
    #[serde(rename = "Numbered")]
    Numbered,
    #[serde(rename = "Other")]
    Other,

}

impl std::fmt::Display for ParkingSpotIdentificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Numbered => write!(f, "Numbered"),
            Self::Other => write!(f, "Other"),
        }
    }
}

impl Default for ParkingSpotIdentificationType {
    fn default() -> ParkingSpotIdentificationType {
        Self::Numbered
    }
}

