/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplySourceCapabilities : The capabilities of a supply source.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplySourceCapabilities {
    #[serde(rename = "outbound", skip_serializing_if = "Option::is_none")]
    pub outbound: Option<Box<models::supply_sources_2020_07_01::OutboundCapability>>,
    #[serde(rename = "services", skip_serializing_if = "Option::is_none")]
    pub services: Option<Box<models::supply_sources_2020_07_01::ServicesCapability>>,
}

impl SupplySourceCapabilities {
    /// The capabilities of a supply source.
    pub fn new() -> SupplySourceCapabilities {
        SupplySourceCapabilities {
            outbound: None,
            services: None,
        }
    }
}

