/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BalanceListing : Struct that holds list of balances on the seller account.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceListing {
    /// Collection that holds list of balances on the account 
    #[serde(rename = "balances", skip_serializing_if = "Option::is_none")]
    pub balances: Option<Vec<models::seller_wallet_2024_03_01::Balance>>,
}

impl BalanceListing {
    /// Struct that holds list of balances on the seller account.
    pub fn new() -> BalanceListing {
        BalanceListing {
            balances: None,
        }
    }
}

