/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeeType : Represents different types of fees that can be applied on a transaction.
/// Represents different types of fees that can be applied on a transaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeeType {
    #[serde(rename = "MISCELLANEOUS_FEE")]
    MiscellaneousFee,
    #[serde(rename = "TAX")]
    Tax,
    #[serde(rename = "TRANSACTION_FEE")]
    TransactionFee,

}

impl std::fmt::Display for FeeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MiscellaneousFee => write!(f, "MISCELLANEOUS_FEE"),
            Self::Tax => write!(f, "TAX"),
            Self::TransactionFee => write!(f, "TRANSACTION_FEE"),
        }
    }
}

impl Default for FeeType {
    fn default() -> FeeType {
        Self::MiscellaneousFee
    }
}

