/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PaymentPreferencePaymentType : Represent a type of payment preference.
/// Represent a type of payment preference.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentPreferencePaymentType {
    #[serde(rename = "PERCENTAGE")]
    Percentage,
    #[serde(rename = "AMOUNT")]
    Amount,

}

impl std::fmt::Display for PaymentPreferencePaymentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Percentage => write!(f, "PERCENTAGE"),
            Self::Amount => write!(f, "AMOUNT"),
        }
    }
}

impl Default for PaymentPreferencePaymentType {
    fn default() -> PaymentPreferencePaymentType {
        Self::Percentage
    }
}

