/*
 * The Selling Partner API for Amazon Seller Wallet Open Banking API
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * The version of the OpenAPI document: 2024-03-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduleExpressionType : Represent a type of schedule transfer expression.
/// Represent a type of schedule transfer expression.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ScheduleExpressionType {
    #[serde(rename = "RECURRING")]
    Recurring,
    #[serde(rename = "ONE_TIME")]
    OneTime,

}

impl std::fmt::Display for ScheduleExpressionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Recurring => write!(f, "RECURRING"),
            Self::OneTime => write!(f, "ONE_TIME"),
        }
    }
}

impl Default for ScheduleExpressionType {
    fn default() -> ScheduleExpressionType {
        Self::Recurring
    }
}

