/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OptionalFulfillmentProgram : An optional enrollment program to return the estimated fees when the offer is fulfilled by Amazon (IsAmazonFulfilled is set to true).
/// An optional enrollment program to return the estimated fees when the offer is fulfilled by Amazon (IsAmazonFulfilled is set to true).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OptionalFulfillmentProgram {
    #[serde(rename = "FBA_CORE")]
    FbaCore,
    #[serde(rename = "FBA_SNL")]
    FbaSnl,
    #[serde(rename = "FBA_EFN")]
    FbaEfn,

}

impl std::fmt::Display for OptionalFulfillmentProgram {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FbaCore => write!(f, "FBA_CORE"),
            Self::FbaSnl => write!(f, "FBA_SNL"),
            Self::FbaEfn => write!(f, "FBA_EFN"),
        }
    }
}

impl Default for OptionalFulfillmentProgram {
    fn default() -> OptionalFulfillmentProgram {
        Self::FbaCore
    }
}

