/*
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, see the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2020-12-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2020-12-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ItemVendorDetailsByMarketplace : Vendor details associated with an Amazon catalog item for the indicated Amazon marketplace.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemVendorDetailsByMarketplace {
    /// Amazon marketplace identifier.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    /// Brand code associated with an Amazon catalog item.
    #[serde(rename = "brandCode", skip_serializing_if = "Option::is_none")]
    pub brand_code: Option<String>,
    /// Product category associated with an Amazon catalog item.
    #[serde(rename = "categoryCode", skip_serializing_if = "Option::is_none")]
    pub category_code: Option<String>,
    /// Manufacturer code associated with an Amazon catalog item.
    #[serde(rename = "manufacturerCode", skip_serializing_if = "Option::is_none")]
    pub manufacturer_code: Option<String>,
    /// Parent vendor code of the manufacturer code.
    #[serde(rename = "manufacturerCodeParent", skip_serializing_if = "Option::is_none")]
    pub manufacturer_code_parent: Option<String>,
    /// Product group associated with an Amazon catalog item.
    #[serde(rename = "productGroup", skip_serializing_if = "Option::is_none")]
    pub product_group: Option<String>,
    /// Replenishment category associated with an Amazon catalog item.
    #[serde(rename = "replenishmentCategory", skip_serializing_if = "Option::is_none")]
    pub replenishment_category: Option<ReplenishmentCategory>,
    /// Product subcategory associated with an Amazon catalog item.
    #[serde(rename = "subcategoryCode", skip_serializing_if = "Option::is_none")]
    pub subcategory_code: Option<String>,
}

impl ItemVendorDetailsByMarketplace {
    /// Vendor details associated with an Amazon catalog item for the indicated Amazon marketplace.
    pub fn new(marketplace_id: String) -> ItemVendorDetailsByMarketplace {
        ItemVendorDetailsByMarketplace {
            marketplace_id,
            brand_code: None,
            category_code: None,
            manufacturer_code: None,
            manufacturer_code_parent: None,
            product_group: None,
            replenishment_category: None,
            subcategory_code: None,
        }
    }
}
/// Replenishment category associated with an Amazon catalog item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReplenishmentCategory {
    #[serde(rename = "ALLOCATED")]
    Allocated,
    #[serde(rename = "BASIC_REPLENISHMENT")]
    BasicReplenishment,
    #[serde(rename = "IN_SEASON")]
    InSeason,
    #[serde(rename = "LIMITED_REPLENISHMENT")]
    LimitedReplenishment,
    #[serde(rename = "MANUFACTURER_OUT_OF_STOCK")]
    ManufacturerOutOfStock,
    #[serde(rename = "NEW_PRODUCT")]
    NewProduct,
    #[serde(rename = "NON_REPLENISHABLE")]
    NonReplenishable,
    #[serde(rename = "NON_STOCKUPABLE")]
    NonStockupable,
    #[serde(rename = "OBSOLETE")]
    Obsolete,
    #[serde(rename = "PLANNED_REPLENISHMENT")]
    PlannedReplenishment,
}

impl Default for ReplenishmentCategory {
    fn default() -> ReplenishmentCategory {
        Self::Allocated
    }
}

