/*
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * The version of the OpenAPI document: 2022-03-23
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateScheduledPackageRequest : The request schema for the `createScheduledPackage` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateScheduledPackageRequest {
    /// An Amazon-defined order identifier. Identifies the order that the seller wants to deliver using Amazon Easy Ship.
    #[serde(rename = "amazonOrderId")]
    pub amazon_order_id: String,
    /// A string of up to 255 characters.
    #[serde(rename = "marketplaceId")]
    pub marketplace_id: String,
    #[serde(rename = "packageDetails")]
    pub package_details: Box<models::easy_ship_2022_03_23::PackageDetails>,
}

impl CreateScheduledPackageRequest {
    /// The request schema for the `createScheduledPackage` operation.
    pub fn new(amazon_order_id: String, marketplace_id: String, package_details: models::easy_ship_2022_03_23::PackageDetails) -> CreateScheduledPackageRequest {
        CreateScheduledPackageRequest {
            amazon_order_id,
            marketplace_id,
            package_details: Box::new(package_details),
        }
    }
}

