/*
 * Selling Partner API for Easy Ship
 *
 * Use the Selling Partner API for Easy Ship to build applications for sellers to manage and ship Amazon Easy Ship orders. With this API, you can get available time slots, schedule and reschedule Easy Ship orders, and print shipping labels, invoices, and warranties. To review the differences in Easy Ship operations by marketplace, refer to [Marketplace support](https://developer-docs.amazon.com/sp-api/docs/easyship-api-v2022-03-23-use-case-guide#marketplace-support).
 *
 * The version of the OpenAPI document: 2022-03-23
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Weight : The weight of the scheduled package
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Weight {
    /// The weight of the package.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<models::easy_ship_2022_03_23::UnitOfWeight>,
}

impl Weight {
    /// The weight of the scheduled package
    pub fn new() -> Weight {
        Weight {
            value: None,
            unit: None,
        }
    }
}

