/*
 * The Selling Partner API for Sellers
 *
 * The [Selling Partner API for Sellers](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) (Sellers API) provides essential information about seller accounts, such as:  - The marketplaces a seller can list in - The default language and currency of a marketplace - Whether the seller has suspended listings  Refer to the [Sellers API reference](https://developer-docs.amazon.com/sp-api/docs/sellers-api-v1-reference) for details about this API's operations, data types, and schemas.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrimaryContact : Information about the seller's primary contact.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrimaryContact {
    /// The full name of the seller's primary contact.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "address")]
    pub address: Box<models::sellers::Address>,
    /// The non-Latin script version of the primary contact's name, if applicable.
    #[serde(rename = "nonLatinName", skip_serializing_if = "Option::is_none")]
    pub non_latin_name: Option<String>,
}

impl PrimaryContact {
    /// Information about the seller's primary contact.
    pub fn new(name: String, address: models::sellers::Address) -> PrimaryContact {
        PrimaryContact {
            name,
            address: Box::new(address),
            non_latin_name: None,
        }
    }
}

