/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CurrencyAmount : Currency type and amount.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyAmount {
    /// Three-digit currency code in ISO 4217 format.
    #[serde(rename = "CurrencyCode")]
    pub currency_code: String,
    /// The currency amount.
    #[serde(rename = "Amount")]
    pub amount: f64,
}

impl CurrencyAmount {
    /// Currency type and amount.
    pub fn new(currency_code: String, amount: f64) -> CurrencyAmount {
        CurrencyAmount {
            currency_code,
            amount,
        }
    }
}

