/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelFormatOptionRequest : Whether to include a packing slip.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelFormatOptionRequest {
    /// When true, include a packing slip with the label.
    #[serde(rename = "IncludePackingSlipWithLabel", skip_serializing_if = "Option::is_none")]
    pub include_packing_slip_with_label: Option<bool>,
}

impl LabelFormatOptionRequest {
    /// Whether to include a packing slip.
    pub fn new() -> LabelFormatOptionRequest {
        LabelFormatOptionRequest {
            include_packing_slip_with_label: None,
        }
    }
}

