/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelFormat : The label format.
/// The label format.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LabelFormat {
    #[serde(rename = "PDF")]
    Pdf,
    #[serde(rename = "PNG")]
    Png,
    #[serde(rename = "ZPL203")]
    Zpl203,
    #[serde(rename = "ZPL300")]
    Zpl300,
    #[serde(rename = "ShippingServiceDefault")]
    ShippingServiceDefault,

}

impl std::fmt::Display for LabelFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pdf => write!(f, "PDF"),
            Self::Png => write!(f, "PNG"),
            Self::Zpl203 => write!(f, "ZPL203"),
            Self::Zpl300 => write!(f, "ZPL300"),
            Self::ShippingServiceDefault => write!(f, "ShippingServiceDefault"),
        }
    }
}

impl Default for LabelFormat {
    fn default() -> LabelFormat {
        Self::Pdf
    }
}

