/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssignAppointmentResourcesResponse : Response schema for the `assignAppointmentResources` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignAppointmentResourcesResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::services::AssignAppointmentResourcesResponsePayload>>,
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::services::Error>>,
}

impl AssignAppointmentResourcesResponse {
    /// Response schema for the `assignAppointmentResources` operation.
    pub fn new() -> AssignAppointmentResourcesResponse {
        AssignAppointmentResourcesResponse {
            payload: None,
            errors: None,
        }
    }
}

