/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssignAppointmentResourcesRequest : Request schema for the `assignAppointmentResources` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignAppointmentResourcesRequest {
    /// List of resources that performs or performed job appointment fulfillment.
    #[serde(rename = "resources")]
    pub resources: Vec<models::services::AppointmentResource>,
}

impl AssignAppointmentResourcesRequest {
    /// Request schema for the `assignAppointmentResources` operation.
    pub fn new(resources: Vec<models::services::AppointmentResource>) -> AssignAppointmentResourcesRequest {
        AssignAppointmentResourcesRequest {
            resources,
        }
    }
}

