/*
 * Selling Partner API for Services
 *
 * With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetServiceJobByServiceJobIdResponse : The response schema for the `getServiceJobByServiceJobId` operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetServiceJobByServiceJobIdResponse {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::services::ServiceJob>>,
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::services::Error>>,
}

impl GetServiceJobByServiceJobIdResponse {
    /// The response schema for the `getServiceJobByServiceJobId` operation.
    pub fn new() -> GetServiceJobByServiceJobIdResponse {
        GetServiceJobByServiceJobIdResponse {
            payload: None,
            errors: None,
        }
    }
}

