/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetShipmentLabels : The response schema for the GetShipmentLabels operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetShipmentLabels {
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Box<models::vendor_shipments::TransportationLabels>>,
    /// A list of error responses returned when a request is unsuccessful.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::vendor_shipments::Error>>,
}

impl GetShipmentLabels {
    /// The response schema for the GetShipmentLabels operation.
    pub fn new() -> GetShipmentLabels {
        GetShipmentLabels {
            payload: None,
            errors: None,
        }
    }
}

