/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShipmentDetails : The request schema for the GetShipmentDetails operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipmentDetails {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::vendor_shipments::Pagination>>,
    /// A list of one or more shipments with underlying details.
    #[serde(rename = "shipments", skip_serializing_if = "Option::is_none")]
    pub shipments: Option<Vec<models::vendor_shipments::Shipment>>,
}

impl ShipmentDetails {
    /// The request schema for the GetShipmentDetails operation.
    pub fn new() -> ShipmentDetails {
        ShipmentDetails {
            pagination: None,
            shipments: None,
        }
    }
}

