/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransportLabel : A list of one or more ShipmentLabels.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransportLabel {
    /// Date on which label is created.
    #[serde(rename = "labelCreateDateTime", skip_serializing_if = "Option::is_none")]
    pub label_create_date_time: Option<String>,
    #[serde(rename = "shipmentInformation", skip_serializing_if = "Option::is_none")]
    pub shipment_information: Option<Box<models::vendor_shipments::ShipmentInformation>>,
    /// Indicates the label data,format and type associated .
    #[serde(rename = "labelData", skip_serializing_if = "Option::is_none")]
    pub label_data: Option<Vec<models::vendor_shipments::LabelData>>,
}

impl TransportLabel {
    /// A list of one or more ShipmentLabels.
    pub fn new() -> TransportLabel {
        TransportLabel {
            label_create_date_time: None,
            shipment_information: None,
            label_data: None,
        }
    }
}

