/*
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitShipmentStatusUpdatesRequest : Represents the request payload for submitting updates to the status of shipments, containing an array of one or more ShipmentStatusUpdate objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitShipmentStatusUpdatesRequest {
    /// Contains a list of one or more ShipmentStatusUpdate objects, each representing an update to the status of a specific shipment.
    #[serde(rename = "shipmentStatusUpdates", skip_serializing_if = "Option::is_none")]
    pub shipment_status_updates: Option<Vec<models::vendor_direct_fulfillment_shipping_v1::ShipmentStatusUpdate>>,
}

impl SubmitShipmentStatusUpdatesRequest {
    /// Represents the request payload for submitting updates to the status of shipments, containing an array of one or more ShipmentStatusUpdate objects.
    pub fn new() -> SubmitShipmentStatusUpdatesRequest {
        SubmitShipmentStatusUpdatesRequest {
            shipment_status_updates: None,
        }
    }
}

