/*
 * The Selling Partner API for Invoices.
 *
 * Use the Selling Partner API for Invoices to retrieve and manage invoice-related operations, which can help selling partners manage their bookkeeping processes.
 *
 * The version of the OpenAPI document: 2024-06-19
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorList : A list of error responses that are returned when a request is unsuccessful.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorList {
    /// List of errors.
    #[serde(rename = "errors")]
    pub errors: Vec<models::invoices_2024_06_19::Error>,
}

impl ErrorList {
    /// A list of error responses that are returned when a request is unsuccessful.
    pub fn new(errors: Vec<models::invoices_2024_06_19::Error>) -> ErrorList {
        ErrorList {
            errors,
        }
    }
}

