/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DistributionPackage : Represents an AWD distribution package.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DistributionPackage {
    #[serde(rename = "contents")]
    pub contents: Box<models::awd_2024_05_09::DistributionPackageContents>,
    #[serde(rename = "measurements")]
    pub measurements: Box<models::awd_2024_05_09::MeasurementData>,
    #[serde(rename = "type")]
    pub r#type: models::awd_2024_05_09::DistributionPackageType,
}

impl DistributionPackage {
    /// Represents an AWD distribution package.
    pub fn new(contents: models::awd_2024_05_09::DistributionPackageContents, measurements: models::awd_2024_05_09::MeasurementData, r#type: models::awd_2024_05_09::DistributionPackageType) -> DistributionPackage {
        DistributionPackage {
            contents: Box::new(contents),
            measurements: Box::new(measurements),
            r#type,
        }
    }
}

