/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboundShipmentStatus : Possible shipment statuses used by shipments.
/// Possible shipment statuses used by shipments.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InboundShipmentStatus {
    #[serde(rename = "CREATED")]
    Created,
    #[serde(rename = "SHIPPED")]
    Shipped,
    #[serde(rename = "IN_TRANSIT")]
    InTransit,
    #[serde(rename = "RECEIVING")]
    Receiving,
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "CLOSED")]
    Closed,
    #[serde(rename = "CANCELLED")]
    Cancelled,

}

impl std::fmt::Display for InboundShipmentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Created => write!(f, "CREATED"),
            Self::Shipped => write!(f, "SHIPPED"),
            Self::InTransit => write!(f, "IN_TRANSIT"),
            Self::Receiving => write!(f, "RECEIVING"),
            Self::Delivered => write!(f, "DELIVERED"),
            Self::Closed => write!(f, "CLOSED"),
            Self::Cancelled => write!(f, "CANCELLED"),
        }
    }
}

impl Default for InboundShipmentStatus {
    fn default() -> InboundShipmentStatus {
        Self::Created
    }
}

