/*
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * The version of the OpenAPI document: 2024-05-09
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelOwner : The entity that labels the products.
/// The entity that labels the products.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LabelOwner {
    #[serde(rename = "AMAZON")]
    Amazon,
    #[serde(rename = "SELF")]
    VariantSelf,

}

impl std::fmt::Display for LabelOwner {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Amazon => write!(f, "AMAZON"),
            Self::VariantSelf => write!(f, "SELF"),
        }
    }
}

impl Default for LabelOwner {
    fn default() -> LabelOwner {
        Self::Amazon
    }
}

