/*
 * Selling Partner API for Direct Fulfillment Inventory Updates
 *
 * The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartyIdentification : Name, address and tax details of a party.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyIdentification {
    /// Assigned identification for the party.
    #[serde(rename = "partyId")]
    pub party_id: String,
}

impl PartyIdentification {
    /// Name, address and tax details of a party.
    pub fn new(party_id: String) -> PartyIdentification {
        PartyIdentification {
            party_id,
        }
    }
}

