/*
 * Selling Partner API for Replenishment
 *
 * The Selling Partner API for Replenishment (Replenishment API) provides programmatic access to replenishment program metrics and offers. These programs provide recurring delivery of any replenishable item at a frequency chosen by the customer.  The Replenishment API is available worldwide wherever Amazon Subscribe & Save is available or is supported. The API is available to vendors and FBA selling partners.
 *
 * The version of the OpenAPI document: 2022-11-07
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Preference : Offer preferences that you can include in the result filter criteria.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Preference {
    /// Filters the results to only include offers with the auto-enrollment preference specified.
    #[serde(rename = "autoEnrollment", skip_serializing_if = "Option::is_none")]
    pub auto_enrollment: Option<Vec<models::replenishment_2022_11_07::AutoEnrollmentPreference>>,
}

impl Preference {
    /// Offer preferences that you can include in the result filter criteria.
    pub fn new() -> Preference {
        Preference {
            auto_enrollment: None,
        }
    }
}

