/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Currency : The type and amount of currency.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Currency {
    /// Decimal value of the currency.
    #[serde(rename = "amount")]
    pub amount: f64,
    /// ISO 4217 standard of a currency code.
    #[serde(rename = "code")]
    pub code: String,
}

impl Currency {
    /// The type and amount of currency.
    pub fn new(amount: f64, code: String) -> Currency {
        Currency {
            amount,
            code,
        }
    }
}

