/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LabelPrintType : Indicates the type of print type for a given label.
/// Indicates the type of print type for a given label.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LabelPrintType {
    #[serde(rename = "STANDARD_FORMAT")]
    StandardFormat,
    #[serde(rename = "THERMAL_PRINTING")]
    ThermalPrinting,

}

impl std::fmt::Display for LabelPrintType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StandardFormat => write!(f, "STANDARD_FORMAT"),
            Self::ThermalPrinting => write!(f, "THERMAL_PRINTING"),
        }
    }
}

impl Default for LabelPrintType {
    fn default() -> LabelPrintType {
        Self::StandardFormat
    }
}

