/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListInboundPlanPalletsResponse : The `listInboundPlanPallets` response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListInboundPlanPalletsResponse {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::fulfillment_inbound_2024_03_20::Pagination>>,
    /// The pallets in an inbound plan.
    #[serde(rename = "pallets")]
    pub pallets: Vec<models::fulfillment_inbound_2024_03_20::Pallet>,
}

impl ListInboundPlanPalletsResponse {
    /// The `listInboundPlanPallets` response.
    pub fn new(pallets: Vec<models::fulfillment_inbound_2024_03_20::Pallet>) -> ListInboundPlanPalletsResponse {
        ListInboundPlanPalletsResponse {
            pagination: None,
            pallets,
        }
    }
}

