/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListShipmentPalletsResponse : The `listShipmentPallets` response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListShipmentPalletsResponse {
    #[serde(rename = "pagination", skip_serializing_if = "Option::is_none")]
    pub pagination: Option<Box<models::fulfillment_inbound_2024_03_20::Pagination>>,
    /// The pallets in a shipment.
    #[serde(rename = "pallets")]
    pub pallets: Vec<models::fulfillment_inbound_2024_03_20::Pallet>,
}

impl ListShipmentPalletsResponse {
    /// The `listShipmentPallets` response.
    pub fn new(pallets: Vec<models::fulfillment_inbound_2024_03_20::Pallet>) -> ListShipmentPalletsResponse {
        ListShipmentPalletsResponse {
            pagination: None,
            pallets,
        }
    }
}

