/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LtlTrackingDetail : Contains information related to Less-Than-Truckload (LTL) shipment tracking.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LtlTrackingDetail {
    /// The number of the carrier shipment acknowledgement document.
    #[serde(rename = "billOfLadingNumber", skip_serializing_if = "Option::is_none")]
    pub bill_of_lading_number: Option<String>,
    /// The number associated with the freight bill.
    #[serde(rename = "freightBillNumber", skip_serializing_if = "Option::is_none")]
    pub freight_bill_number: Option<Vec<String>>,
}

impl LtlTrackingDetail {
    /// Contains information related to Less-Than-Truckload (LTL) shipment tracking.
    pub fn new() -> LtlTrackingDetail {
        LtlTrackingDetail {
            bill_of_lading_number: None,
            freight_bill_number: None,
        }
    }
}

