/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MskuQuantity : Represents an MSKU and the related quantity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MskuQuantity {
    /// The merchant SKU, a merchant-supplied identifier for a specific SKU.
    #[serde(rename = "msku")]
    pub msku: String,
    /// A positive integer.
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl MskuQuantity {
    /// Represents an MSKU and the related quantity.
    pub fn new(msku: String, quantity: i32) -> MskuQuantity {
        MskuQuantity {
            msku,
            quantity,
        }
    }
}

