/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectedDeliveryWindow : Selected delivery window attributes.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedDeliveryWindow {
    /// Identifies type of Delivery Window Availability. Values: `AVAILABLE`, `CONGESTED`
    #[serde(rename = "availabilityType")]
    pub availability_type: String,
    /// Identifier of a delivery window option. A delivery window option represent one option for when a shipment is expected to be delivered.
    #[serde(rename = "deliveryWindowOptionId")]
    pub delivery_window_option_id: String,
    /// The timestamp at which this Window can no longer be edited.
    #[serde(rename = "editableUntil", skip_serializing_if = "Option::is_none")]
    pub editable_until: Option<String>,
    /// The end timestamp of the window.
    #[serde(rename = "endDate")]
    pub end_date: String,
    /// The start timestamp of the window.
    #[serde(rename = "startDate")]
    pub start_date: String,
}

impl SelectedDeliveryWindow {
    /// Selected delivery window attributes.
    pub fn new(availability_type: String, delivery_window_option_id: String, end_date: String, start_date: String) -> SelectedDeliveryWindow {
        SelectedDeliveryWindow {
            availability_type,
            delivery_window_option_id,
            editable_until: None,
            end_date,
            start_date,
        }
    }
}

