/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelfShipAppointmentDetails : Appointment details for carrier pickup or fulfillment center appointments.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelfShipAppointmentDetails {
    /// Identifier for appointment.
    #[serde(rename = "appointmentId", skip_serializing_if = "Option::is_none")]
    pub appointment_id: Option<f64>,
    #[serde(rename = "appointmentSlotTime", skip_serializing_if = "Option::is_none")]
    pub appointment_slot_time: Option<Box<models::fulfillment_inbound_2024_03_20::AppointmentSlotTime>>,
    /// Status of the appointment.
    #[serde(rename = "appointmentStatus", skip_serializing_if = "Option::is_none")]
    pub appointment_status: Option<String>,
}

impl SelfShipAppointmentDetails {
    /// Appointment details for carrier pickup or fulfillment center appointments.
    pub fn new() -> SelfShipAppointmentDetails {
        SelfShipAppointmentDetails {
            appointment_id: None,
            appointment_slot_time: None,
            appointment_status: None,
        }
    }
}

