/*
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * The version of the OpenAPI document: 2024-03-20
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShipmentSource : Specifies the 'ship from' address for the shipment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShipmentSource {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::fulfillment_inbound_2024_03_20::Address>>,
    /// The type of source for this shipment. Possible values: `SELLER_FACILITY`.
    #[serde(rename = "sourceType")]
    pub source_type: String,
}

impl ShipmentSource {
    /// Specifies the 'ship from' address for the shipment.
    pub fn new(source_type: String) -> ShipmentSource {
        ShipmentSource {
            address: None,
            source_type,
        }
    }
}

